### ISSUE TITLE
Infinite re-rendering caused by calling `useVoice()`

### ISSUE THREAD

**Issue by lasryaric** [HumeAI/empathic-voice-api-js#288]
Hi, I found that there is an infinite re-rendering in my component as soon as I called `useVoice()`.

Here is a very simple code that create this infinite re-rendering, I am using `"@humeai/voice-react": "0.1.18"`.

`/components/chat_with_voice.tsx`
```typescript
"use client";

import { useVoice, VoiceProvider } from "@humeai/voice-react";
import { Message } from "ai";
import { Chat } from "@/components/chat";
import { VoiceTest } from "./voice_test";

export function ChatWithVoice({
  accessToken,
}: {
  initialMessages: Array<Message>;
  selectedModelId: string;
  accessToken: string;
}) {
  return (
    <VoiceProvider
      configId="...."
      auth={{ type: "accessToken", value: accessToken }}
    >
      <VoiceTest />
    </VoiceProvider>
  );
}
```

`/components/voice_test.tsx`
```typescript
import { useVoice } from "@humeai/voice-react";
import { Button } from "./ui/button";
import { useEffect } from "react";

export function VoiceTest() {
  const { status, connect, mute, muteAudio } = useVoice();
  console.log("rendering ************");
  useEffect(() => {
    muteAudio();
    mute();
  }, [mute, muteAudio]);
  return (
    <div>
      <Button onClick={() => connect()}>Connect</Button>
      <div>{status.value}</div>
    </div>
  );
}
```

I even called `muteAudio()` and `mute()` to make sure the re-rendering is not triggered by the `micFft` or `fft` values changing.

The React profiler shows that the `VoiceTest` component is re-rendering because the `VoiceProvider` context provider had hook 77 change. This only happens once I call the `connect()` function. After that, I don't do anything and I can observe a lot of `rendering********` logs in my console. Please see attached screenshot for the profiler recording.

<img width="1263" alt="Screenshot 2024-11-20 at 17 58 26" src="https://github.com/user-attachments/assets/2b6cdc17-1a4b-43e0-a44b-a6579becb39a">

Please let me know how we can fix that and how I can help.

**Comment by lasryaric** [comment]
So reading the [Discord](https://discord.com/channels/991790422433210459/991794453109022782/1308841533209972807), I understand that you think is expected, but the problem I have then is that I can't have a component that calls `connect()` on mount and `disconnect()` on un-mout, which I think should work:

The following implementation  connects and disconnects in an infinite loop, even though this is the recommended way of cleaning up resources and side effects in a React componenent.

```
import { useVoice } from "@humeai/voice-react";
import { Button } from "./ui/button";
import { useEffect } from "react";

export function VoiceTest() {
  const { status, connect, disconnect } = useVoice();
  console.log("rendering ************");
  useEffect(() => {
    connect();

    return () => {
      disconnect();
    };
  }, [connect, disconnect]);

  useEffect(() => {
    console.log("status", status.value);
  }, [status]);

  return (
    <div>
      <div>{status.value}</div>
    </div>
  );
}

```

**Comment by yinishi** [comment]
We discussed this issue in the Hume discord channel, but posting here for posterity:

VoiceProvider does rerender frequently because of fast and frequent state changes due to audio and mic FFT, so it's different from a classic "infinite" rerender in the sense that the renders are expected. I can provide you with some recommendations that will help your case here.

1. re: calling connect in a useEffect: Generally we would recommend that users trigger a connect call off of a user action, ie a button click. This is in fact a browser requirement, because the AudioContext element requires a user action to initialize correctly. By calling connect on mount, the assistant will not initialize correctly, particularly in Safari. I understand this isn't entirely clear in our documentation, so I'll take it as an action item on our end to include that detail in the README
2. re: calling disconnect in a useEffect to disconnect on unmount: VoiceProvider currently already performs this cleanup on unmount. If you are seeing otherwise, however, please let me know and we can look into it!
3. re: rerendering recommendations in using the React SDK: because of the frequent state changes, I'd definitely recommend that VoiceProvider wraps only the part of your application that needs to be aware of EVI state. Another recommendation is that if you are using methods from useVoice in a dependency array, you can use a ref or a helper hook like useLatest to create stable dependencies: https://github.com/streamich/react-use/blob/master/docs/useLatest.md
